# Generated by Django 4.0 on 2022-04-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='Product',
        ),
    ]
